version: "3"

services:
 app:
  build: '.'
  restart: always
  container_name: ticketsMB-teste
  command: npm run migrate && npm dev
  ports: 
    - "3000:3000"
  volumes: 
    - .:/urs/app
  links: 
    - mongo-ticket
    - postgres-ticket
  depends_on:
    - mongo-ticket
    - postgres-ticket

  postgres-ticket:
    container_name: postgres-ticket
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-ticket-data:/data
    networks:
      - app-connect

  mongo-ticket:
    container_name: mongo-ticket
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-ticket-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

networks:
  app-connect:

  
   

         
  